version : '3.8'

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/tipsproject
    expose:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/tipsproject/static
    depends_on:
      - web


volumes:
  postgres_data:


